name: Check Hyperlinks

on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2

      - name: Check links in README.md
        uses: lycheeverse/lychee-action@master
        with:
          args: README.md # Specify the file to check
